name: Blog Workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 9 * * *'
  workflow_dispatch: 

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          commit_message: "Cron job: Updated blog post list"
          feed_list: "https://rahatzamancse.netlify.app/en/index.xml"
