name: SO Workflow
on:
  schedule:
    # Runs every hour
    - cron: '0 8 * * *'
  workflow_dispatch: 

jobs:
  update-readme-with-stackoverflow:
    name: Update this repo's README with latest stackoverflow updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "STACKOVERFLOW-LIST"
          commit_message: "Cron job: Updated stackoverflow list"
          feed_list: "https://stackoverflow.com/feeds/user/6452525"
